### ISSUE TITLE
:erlang.open_port error

### ISSUE THREAD

**Issue by mauricionr** [amolenaar/elixir-brewberry-pi#5]
```
Generated fw_rpi app
MacBook-Pro-de-Mauririo:brewberry-pi mauririonunes$ iex -S mix
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Env
  MIX_ENV:  dev
  target:   host


19:10:03.933 [info]  Start Network Interface Worker

19:10:03.992 [info]  Application nerves_network_interface exited: Nerves.NetworkInterface.Application.start(:normal, []) returned an error: shutdown: failed to start child: Nerves.NetworkInterface.Worker
    ** (EXIT) an exception was raised:
        ** (ErlangError) Erlang error: :enoent
            :erlang.open_port({:spawn_executable, '/Users/mauririonunes/workspace/brewberry-pi/_build/dev/lib/nerves_network_interface/priv/netif'}, [{:packet, 2}, :use_stdio, :binary])
            (nerves_network_interface) lib/network_interface/worker.ex:123: Nerves.NetworkInterface.Worker.init/1
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

19:10:03.992 [info]  Application nerves_wpa_supplicant exited: :stopped
** (Mix) Could not start application nerves_network_interface: Nerves.NetworkInterface.Application.start(:normal, []) returned an error: shutdown: failed to start child: Nerves.NetworkInterface.Worker
    ** (EXIT) an exception was raised:
        ** (ErlangError) Erlang error: :enoent
            :erlang.open_port({:spawn_executable, '/Users/mauririonunes/workspace/brewberry-pi/_build/dev/lib/nerves_network_interface/priv/netif'}, [{:packet, 2}, :use_stdio, :binary])
            (nerves_network_interface) lib/network_interface/worker.ex:123: Nerves.NetworkInterface.Worker.init/1
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
MacBook-Pro-de-Mauririo:brewberry-pi mauririonunes$ 
```

```
MacBook-Pro-de-Mauririo:brewberry-pi mauririonunes$ elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0
MacBook-Pro-de-Mauririo:brewberry-pi mauririonunes$ 
```

**Comment by mauricionr** [comment]
on ubuntu i had the same erlang and elixir versions

**Comment by mauricionr** [comment]
i guess i figure it out how to run dev mode on mac, 

in this file `brewery-pi/apps/fw_rpi/mix.exs` i uncomment the first line and comment the other one and it works

```
  @target System.get_env("MIX_TARGET") || :host
  # @target if Mix.env == :prod, do: :rpi, else: :host
```

am'i right?
